-- Create table for exercises
CREATE TABLE exercises (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    muscle_group VARCHAR(100) NOT NULL
);

-- Inserting the top 100 most popular gym exercises with their muscle groups
INSERT INTO exercises (name, muscle_group) VALUES 
    (NULL, 'Push-Up', 'Chest'),
    (NULL, 'Pull-Up', 'Back'),
    (NULL, 'Squat', 'Legs'),
    (NULL, 'Deadlift', 'Legs'),
    (NULL, 'Bench Press', 'Chest'),
    (NULL, 'Shoulder Press', 'Shoulders'),
    (NULL, 'Barbell Row', 'Back'),
    (NULL, 'Bicep Curl', 'Biceps'),
    (NULL, 'Tricep Dip', 'Triceps'),
    (NULL, 'Plank', 'Core'),
    (NULL, 'Russian Twist', 'Core'),
    (NULL, 'Leg Press', 'Legs'),
    (NULL, 'Lunges', 'Legs'),
    (NULL, 'Leg Curl', 'Legs'),
    (NULL, 'Leg Extension', 'Legs'),
    (NULL, 'Calf Raise', 'Legs'),
    (NULL, 'Incline Bench Press', 'Chest'),
    (NULL, 'Decline Bench Press', 'Chest'),
    (NULL, 'Chest Fly', 'Chest'),
    (NULL, 'Pulldown', 'Back'),
    (NULL, 'Lat Pulldown', 'Back'),
    (NULL, 'Seated Row', 'Back'),
    (NULL, 'Dumbbell Press', 'Shoulders'),
    (NULL, 'Dumbbell Fly', 'Chest'),
    (NULL, 'Dumbbell Row', 'Back'),
    (NULL, 'Dumbbell Curl', 'Biceps'),
    (NULL, 'Dumbbell Tricep Extension', 'Triceps'),
    (NULL, 'Skull Crushers', 'Triceps'),
    (NULL, 'Arnold Press', 'Shoulders'),
    (NULL, 'Front Raise', 'Shoulders'),
    (NULL, 'Lateral Raise', 'Shoulders'),
    (NULL, 'Reverse Fly', 'Back'),
    (NULL, 'Hyperextension', 'Back'),
    (NULL, 'Romanian Deadlift', 'Legs'),
    (NULL, 'Hack Squat', 'Legs'),
    (NULL, 'Box Jump', 'Legs'),
    (NULL, 'Step-Up', 'Legs'),
    (NULL, 'Burpees', 'Full Body'),
    (NULL, 'Mountain Climbers', 'Core'),
    (NULL, 'Sit-Up', 'Core'),
    (NULL, 'Hanging Leg Raise', 'Core'),
    (NULL, 'Dips', 'Triceps'),
    (NULL, 'Tricep Kickback', 'Triceps'),
    (NULL, 'Close-Grip Bench Press', 'Triceps'),
    (NULL, 'Hammer Curl', 'Biceps'),
    (NULL, 'Preacher Curl', 'Biceps'),
    (NULL, 'Concentration Curl', 'Biceps'),
    (NULL, 'Machine Chest Press', 'Chest'),
    (NULL, 'Machine Shoulder Press', 'Shoulders'),
    (NULL, 'Machine Pulldown', 'Back'),
    (NULL, 'Machine Row', 'Back'),
    (NULL, 'Machine Leg Press', 'Legs'),
    (NULL, 'Machine Leg Curl', 'Legs'),
    (NULL, 'Machine Leg Extension', 'Legs'),
    (NULL, 'Machine Calf Raise', 'Legs'),
    (NULL, 'Machine Fly', 'Chest'),
    (NULL, 'Cable Crossover', 'Chest'),
    (NULL, 'Cable Row', 'Back'),
    (NULL, 'Cable Pulldown', 'Back'),
    (NULL, 'Cable Curl', 'Biceps'),
    (NULL, 'Cable Tricep Pushdown', 'Triceps'),
    (NULL, 'Cable Lateral Raise', 'Shoulders'),
    (NULL, 'Cable Crunch', 'Core'),
    (NULL, 'Russian Twist', 'Core'),
    (NULL, 'Oblique Crunch', 'Core'),
    (NULL, 'Plank Shoulder Tap', 'Core'),
    (NULL, 'Leg Raises', 'Core'),
    (NULL, 'Side Plank', 'Core'),
    (NULL, 'Sissy Squat', 'Legs'),
    (NULL, 'Hack Squat', 'Legs'),
    (NULL, 'Leg Press', 'Legs'),
    (NULL, 'Seated Leg Curl', 'Legs'),
    (NULL, 'Standing Calf Raise', 'Legs'),
    (NULL, 'Dumbbell Bench Press', 'Chest'),
    (NULL, 'Dumbbell Shoulder Press', 'Shoulders'),
    (NULL, 'Dumbbell Lateral Raise', 'Shoulders'),
    (NULL, 'Dumbbell Front Raise', 'Shoulders'),
    (NULL, 'Dumbbell Shrugs', 'Shoulders'),
    (NULL, 'Dumbbell Pullover', 'Back'),
    (NULL, 'Dumbbell Deadlift', 'Back'),
    (NULL, 'Dumbbell Squat', 'Legs'),
    (NULL, 'Dumbbell Lunges', 'Legs'),
    (NULL, 'Dumbbell Step-Up', 'Legs');

-- Describe the 'exercises' table
DESC exercises;
